/**
 * Writes ASSETS.md — the list of files the current content pack needs.
 *
 * It derives everything from src/lib/data, so editing a scene and re-running
 * this keeps the upload checklist honest. The library's own `assetManifest()`
 * does the work; this only formats it.
 *
 *   npm run assets
 *   npm run assets -- --base=/media --ext=m4a
 */
import { build } from "esbuild";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const arg = (name, fallback) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};

const base = arg("base", "/audio");
const ext = arg("ext", "ogg");
const out = arg("out", "ASSETS.md");

const dir = mkdtempSync(join(tmpdir(), "ambience-manifest-"));
const bundle = join(dir, "pack.mjs");
await build({
  entryPoints: ["src/manifest-entry.ts"],
  outfile: bundle,
  bundle: true,
  format: "esm",
  platform: "node",
  logLevel: "warning",
});

const {
  DEFAULT_CONFIG,
  assetManifest,
  manifestSummary,
  assetLayout,
  motifSeconds,
  poolSeconds,
  variantMotifs,
  SCENE_BRIEFS,
  BED_NOTES,
  ONE_SHOT_NOTES,
} = await import(pathToFileURL(bundle).href);
rmSync(dir, { recursive: true, force: true });

const config = DEFAULT_CONFIG;
const resolveSrc = assetLayout({ base, ext });
const entries = assetManifest(config, { resolveSrc });
const summary = manifestSummary(config, { resolveSrc });
const music = entries.filter((e) => e.kind === "music");
const beds = entries.filter((e) => e.kind === "bed");
const oneShots = entries.filter((e) => e.kind === "one-shot");

const mmss = (s) => `${Math.floor(s / 60)}:${String(Math.round(s % 60)).padStart(2, "0")}`;
const uniqueSeconds = summary.byTheme.reduce((n, t) => n + t.seconds, 0);
/** A 45 s stereo stem at 44.1 kHz is ~15.9 MB decoded. */
const mbPerStem = (secs) => (secs * 44100 * 2 * 4) / (1024 * 1024);
const worstMotif = Math.max(...config.themes.map((t) => motifSeconds(t.bpm, t.bars)));
const worstLayers = Math.max(...summary.byTheme.map((t) => t.intensities));

const lines = [];
const w = (s = "") => lines.push(s);

w("# Required assets");
w();
w("<!-- Generated by `npm run assets`. Edit src/lib/data, not this file. -->");
w();
w(
  `**${summary.total} files**: ${summary.music} music files across ${config.themes.length} scenes, ` +
    `${summary.beds} ambience beds and ${summary.oneShots} one-shots. That is ${mmss(uniqueSeconds)} of ` +
    `unique music once, not per intensity. Paths assume \`assetLayout({ base: "${base}", ext: "${ext}" })\`.`
);
w();

w("## How the music is built");
w();
w(
  "A scene's score is a **pool of motifs** — short passages, chained in a shuffled order so " +
    "the music runs for minutes without the sequence coming round. A motif that has just played " +
    "will not be picked again for another few motifs, so the shuffle never doubles back on itself. " +
    "Each motif is recorded at several **intensity levels**, which is how the arrangement thickens " +
    "as a scene heats up."
);
w();
w("So for a four-level scene, one motif is four files of the same passage:");
w();
w("```");
w("intensity-1.ogg   strings");
w("intensity-2.ogg   strings + piano");
w("intensity-3.ogg   strings + piano + bass");
w("intensity-4.ogg   strings + piano + bass + counter-melody");
w("```");
w();
w(
  "**Each file is a complete mix at that level**, not an additive stem. Changing intensity " +
    "crossfades to that level of the *same motif at the same point in the passage*, which is why " +
    "every level has to exist for every motif — there is no level 2 of motif 3 to cross to if it " +
    "was never bounced. Bounce them from one session so they line up sample for sample."
);
w();
w(
  "The engine also supports the additive alternative — `intensityMode: \"layers\"`, where each file " +
    "holds only its own instruments and they sum. Same file count, and the console can A/B them: " +
    "`npm run dev` then the `intensity model` switch in the demo. Name additive files `layer-1.ogg` " +
    "and pass `assetLayout({ musicPrefix: \"layer\" })`."
);
w();
w(
  "Exploration and combat are separate pools, not two versions of the same passage. Switching " +
    "mode crossfades from one pool into the other, so combat can be its own music rather than " +
    "a busier arrangement of the same cue."
);
w();

w("## Why motifs, and not one long piece");
w();
w(
  `Decoded audio is uncompressed. A ${Math.round(worstMotif)} s stereo stem at 44.1 kHz occupies about ` +
    `${mbPerStem(worstMotif).toFixed(0)} MB in memory however small the .ogg is — so a five-minute layered stem ` +
    "would be about 106 MB, and one scene's worth would run past a gigabyte. Long-form music cannot be " +
    "held as buffers, and buffers are what make the layers line up sample for sample."
);
w();
w(
  "Chaining short motifs is the way out. Only the sounding motif and the one queued behind it are " +
    "ever *required* to be resident, so the floor is:"
);
w();
// mixes mode sounds one file at a time, two only while an intensity crossfade runs
const musicFloor = mbPerStem(worstMotif) * 2 * 2;
const bedFloor = mbPerStem(60) * 6;
w("```");
const row = (label, value) => w(label.padEnd(38) + value);
row(`music   ${Math.round(worstMotif)} s x 2 motifs x 2 during a crossfade`, `~${musicFloor.toFixed(0)} MB`);
row("beds    6 up at once x 60 s", `~${bedFloor.toFixed(0)} MB`);
row("", "-".repeat(9));
row("total", `~${(musicFloor + bedFloor).toFixed(0)} MB stereo`);
row("", `~${((musicFloor + bedFloor) / 2).toFixed(0)} MB mono`);
w("```");
w();
w(
  "**Mono halves it.** Ambience beds and single-instrument layers rarely need stereo; keep it for " +
    "pads, strings and anything meant to sit wide. That one choice is the difference between a " +
    "comfortable footprint and a heavy one."
);
w();
w(
  "Above that floor the console keeps whatever else it has already decoded, so a motif coming round " +
    "again usually costs nothing, and evicts least-recently-used as it approaches `maxDecodedBytes` " +
    "(default 320 MB). Audio that is currently sounding is never evicted, so the floor above is a " +
    "true floor. Neither figure grows with how long the session runs. Lower the ceiling for tablets; " +
    "the cost is a re-fetch when a motif returns, which has the queue lead (10 s) to complete in."
);
w();

w("## Format");
w();
w("| | |");
w("|---|---|");
w("| Container | **Ogg Vorbis** (`.ogg`). See the note on MP3 below. |");
w("| Sample rate | 48 kHz, or 44.1 kHz — one or the other throughout. |");
w("| Channels | Stereo for wide beds and full layers; **mono halves the memory** and suits single instruments. |");
w("| Music level | Mix each intensity level to about −18 LUFS, matched across levels so a crossfade does not jump. |");
w("| Bed level | Normalise each bed to about −20 LUFS. The console applies −18/−12/−6 dB on top. |");
w("| Bed length | 30–90 s, and give beds in one scene different lengths so they do not lock into a pattern. |");
w();
w(
  "Motifs are chained by scheduling the next one to start the sample after the last one ends, so " +
    "**every intensity level of a motif must be exactly the same length** and must not carry silence at either " +
    "end. Ring-outs that cross the join should be printed into the head of the next motif, or left " +
    "to the reverb tail of the stem itself."
);
w();
w(
  "**Avoid MP3.** The encoder pads both ends, and the padding survives decoding: motifs would no " +
    "longer butt up cleanly and the layers of one motif would not line up. Ogg Vorbis, Opus and WAV " +
    "do not. If you need a Safari fallback, serve `.m4a` from `resolveSrc` by feature test."
);
w();

w("## Music, scene by scene");
w();
w("| Scene | Tempo | Key | Motif length | Motifs | Levels | Files | Unique music |");
w("|---|---|---|---|---|---|---|---|");
for (const theme of config.themes) {
  const info = summary.byTheme.find((t) => t.themeId === theme.id);
  w(
    `| ${theme.name} | ${theme.bpm} BPM | ${theme.key} | ${theme.bars} bars · ${motifSeconds(theme.bpm, theme.bars).toFixed(1)} s | ` +
      `${info.motifs} | ${info.intensities} | ${info.music} | ${mmss(info.seconds)} |`
  );
}
w();

for (const theme of config.themes) {
  const info = summary.byTheme.find((t) => t.themeId === theme.id);
  w(`### ${theme.name}`);
  w();
  w(
    `\`${theme.id}\` · ${theme.bpm} BPM · ${theme.key} · ${theme.bars} bars per motif ` +
      `(${motifSeconds(theme.bpm, theme.bars).toFixed(1)} s) · ${info.intensities} intensity levels`
  );
  w();
  const brief = SCENE_BRIEFS[theme.id];
  if (brief) {
    w(`> ${brief.premise}`);
    w();
    w(`**Palette.** ${brief.palette}`);
    w();
    w("**Intensity levels** — each file is the complete mix at that level, not just the part being added:");
    w();
    brief.levels.forEach((text, i) => w(`${i + 1}. ${text}`));
    w();
    w(`**Combat pool.** ${brief.combat}`);
    w();
  }

  for (const variant of theme.variants) {
    const ex = poolSeconds(config, theme.id, variant.id, "explore");
    const co = poolSeconds(config, theme.id, variant.id, "combat");
    const ids = variantMotifs(theme, variant).map((m) => m.id);
    w(
      `- **${variant.name}** draws on ${ids.length} motifs — exploration runs ${mmss(ex)} ` +
        `and combat ${mmss(co)} before the order refreshes.`
    );
  }
  w();
  for (const mode of ["explore", "combat"]) {
    const rows = music.filter((m) => m.themeId === theme.id && m.mode === mode);
    const ids = [...new Set(rows.map((r) => r.motifId))];
    if (ids.length === 0) continue;
    w(`**${mode === "explore" ? "Exploration" : "Combat"} pool** — ${ids.length} motifs`);
    w();
    w("```");
    for (const e of rows) w(e.url);
    w("```");
    w();
  }
}

w("## Ambience beds");
w();
w(
  "One flat folder; the id is the filename. Beds listed by a scene are the ones it opens with — " +
    "the rest of the library is reachable from the console's search, so all of them are worth having."
);
w();
w("| File | Name | Opens with | Notes |");
w("|---|---|---|---|");
for (const bed of beds) {
  const note = BED_NOTES[bed.bedId] ?? "";
  w(`| \`${bed.url}\` | ${bed.label} | ${bed.usedBy.length ? bed.usedBy.join(", ") : "—"} | ${note} |`);
}
w();

w("## One-shots");
w();
w(
  "Fired by hand, played once over the top of everything on their own bus. Short — under a few " +
    "seconds — and normalised a little hotter than the beds, around −16 LUFS, since they are meant " +
    "to cut through."
);
w();
for (const [group, note] of Object.entries(ONE_SHOT_NOTES)) w(`- **${group}.** ${note}`);
w();
w("| File | Name | Group |");
w("|---|---|---|");
for (const o of oneShots) w(`| \`${o.url}\` | ${o.label} | ${o.group ?? "—"} |`);
w();

w("## Producing this in order");
w();
const perScene = summary.byTheme[0];
w(
  `1. **One exploration motif per scene, every level** (${config.themes.length} motifs, ` +
    `~${config.themes.reduce((n, t) => n + (summary.byTheme.find((s) => s.themeId === t.id)?.intensities ?? 4), 0)} files). ` +
    "Every scene plays, and intensity works. This is the smallest thing worth demoing."
);
w(
  `2. **Scene beds** (${config.themes.reduce((n, t) => n + t.ambience.length, 0)} files, some shared). ` +
    "Most of the atmosphere lives here, and beds are far quicker to produce than scored motifs."
);
w("3. **The rest of each exploration pool** — the shuffle has enough material to stop feeling like a loop.");
w("4. **Combat pools** — the combat toggle starts working.");
w("5. **The rest of the bed library**, for the search.");
w();
w(
  "Until a file exists, keep it out of the resolver so the console stays quiet about it: " +
    "`assetLayout({ base, ext, available: urlsYouHaveUploaded })` returns `null` for anything not in " +
    "the set, and `missingAssets(config, uploaded)` lists what is still outstanding."
);
w();
w("### Levers, if this is too much");
w();
w(
  `Unique music scales with **motifs × scenes**, and file count with **× layers**. Today: ` +
    `${config.themes.length} scenes × ${perScene.motifs} motifs × ~${worstLayers} intensity levels. Halving the pool to ` +
    "four exploration and two combat motifs per scene halves both, at the cost of the order coming " +
    "round twice as fast. Dropping a scene removes its whole column. Cutting a level removes one file " +
    "per motif and one step from the intensity control.\n\nThe honest floor: **" +
    `${config.themes.length} scenes × 1 exploration motif × 4 levels = ${config.themes.length * 4} music files** ` +
    "plus the beds. Everything above that buys variety, not function."
);

writeFileSync(out, lines.join("\n"));

console.log(`${out}: ${summary.total} files (${summary.music} music, ${summary.beds} beds, ${summary.oneShots} one-shots)`);
console.log(`unique music: ${mmss(uniqueSeconds)}`);
for (const t of summary.byTheme) {
  console.log(`  ${t.name.padEnd(18)} ${t.motifs} motifs x ${t.intensities} levels = ${t.music} files`);
}
