/**
 * Writes ASSETS.md — the list of files the current content pack needs.
 *
 * It derives everything from src/lib/data, so editing a scene and re-running
 * this keeps the upload checklist honest. The library's own `assetManifest()`
 * does the work; this only formats it.
 *
 *   npm run assets                       # default layout, /audio, .ogg
 *   npm run assets -- --base=/media --ext=m4a
 */
import { build } from "esbuild";
import { mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";

const arg = (name, fallback) => {
  const hit = process.argv.find((a) => a.startsWith(`--${name}=`));
  return hit ? hit.slice(name.length + 3) : fallback;
};

const base = arg("base", "/audio");
const ext = arg("ext", "ogg");
const out = arg("out", "ASSETS.md");

// bundle the TS sources to something Node can import directly
const dir = mkdtempSync(join(tmpdir(), "ambience-manifest-"));
const bundle = join(dir, "pack.mjs");
await build({
  entryPoints: ["src/manifest-entry.ts"],
  outfile: bundle,
  bundle: true,
  format: "esm",
  platform: "node",
  logLevel: "warning",
});

const { DEFAULT_CONFIG, assetManifest, manifestSummary, assetLayout, layerCount } = await import(
  pathToFileURL(bundle).href
);
rmSync(dir, { recursive: true, force: true });

const resolveSrc = assetLayout({ base, ext });
const entries = assetManifest(DEFAULT_CONFIG, { resolveSrc });
const summary = manifestSummary(DEFAULT_CONFIG, { resolveSrc });
const music = entries.filter((e) => e.kind === "music");
const beds = entries.filter((e) => e.kind === "bed");

const seconds = (theme) => ((60 / (theme.bpm ?? 90)) * 4 * (theme.bars ?? 8)).toFixed(2);

const lines = [];
const w = (s = "") => lines.push(s);

w("# Required assets");
w();
w("<!-- Generated by `npm run assets`. Edit src/lib/data, not this file. -->");
w();
w(
  `**${summary.total} files**: ${summary.music} music stems across ${DEFAULT_CONFIG.themes.length} scenes, ` +
    `plus ${summary.beds} ambience beds. Paths assume \`assetLayout({ base: "${base}", ext: "${ext}" })\`.`
);
w();

w("## Format");
w();
w("| | |");
w("|---|---|");
w("| Container | **Ogg Vorbis** (`.ogg`) for everything. See the note on MP3 below. |");
w("| Sample rate | 48 kHz, or 44.1 kHz — one or the other throughout. |");
w("| Channels | Stereo for music and wide beds; mono is fine for point sources. |");
w("| Music level | Mix each stack as a whole, around −18 LUFS integrated, true peak ≤ −1 dBTP. |");
w("| Bed level | Normalise each bed to about −20 LUFS. The console applies −18/−12/−6 dB on top. |");
w("| Bed length | 30–90 s. Give beds in the same scene different lengths so they do not lock into a pattern. |");
w();
w(
  "Loops are played with `loop = true`, which is sample-exact and does no crossfading — " +
    "the file itself has to loop cleanly. **Avoid MP3 for music stems**: the encoder adds " +
    "padding at both ends that survives decoding, so the loop drifts off the bar grid and " +
    "clicks once per pass. Ogg Vorbis, Opus and WAV do not. If you need a Safari fallback, " +
    "serve `.m4a` from `resolveSrc` by feature test and accept it for beds only."
);
w();

w("## Music");
w();
w(
  "Every stem of a scene starts on the same sample and runs for the life of the scene; " +
    "intensity and mode only move gain. So all stems of one **variant** — both stacks — must " +
    "be the same length, at the same tempo, bounced from one session with layers soloed. " +
    "Layer 1 is heard alone at intensity 1; each further layer is added on top."
);
w();
w("| Scene | Tempo | Key | Loop | Stems |");
w("|---|---|---|---|---|");
for (const theme of DEFAULT_CONFIG.themes) {
  const info = summary.byTheme.find((t) => t.themeId === theme.id);
  w(
    `| ${theme.name} | ${theme.bpm} BPM | ${theme.key} | ${theme.bars} bars · ${seconds(theme)} s | ${info.music} |`
  );
}
w();

for (const theme of DEFAULT_CONFIG.themes) {
  w(`### ${theme.name}`);
  w();
  w(`\`${theme.id}\` · ${theme.bpm} BPM · ${theme.key} · ${theme.bars} bars (${seconds(theme)} s per loop)`);
  w();
  for (const variant of theme.variants) {
    w(`**${variant.name}** — ${layerCount(variant)} layers per stack`);
    w();
    w("```");
    for (const e of music.filter((m) => m.themeId === theme.id && m.variantId === variant.id)) {
      w(e.url);
    }
    w("```");
    w();
  }
}

w("## Ambience beds");
w();
w(
  "One flat folder; the id is the filename. Beds listed by a scene are the ones it opens " +
    "with — the rest of the library is reachable from the console's search, so all of them " +
    "are worth having."
);
w();
w("| File | Name | Opens with |");
w("|---|---|---|");
for (const bed of beds) {
  w(`| \`${bed.url}\` | ${bed.label} | ${bed.usedBy.length ? bed.usedBy.join(", ") : "—"} |`);
}
w();

w("## Producing this in order");
w();
const tier1 = DEFAULT_CONFIG.themes.length;
const tier2 = DEFAULT_CONFIG.themes.reduce((n, t) => n + t.ambience.length, 0);
w(
  `1. **Explore layer 1 for each scene** (${tier1} files). Every scene plays at intensity 1. ` +
    `This is the smallest thing that is worth demoing.`
);
w(`2. **Scene beds** (${tier2} files, some shared). This is where most of the atmosphere lives.`);
w(`3. **Explore layers 2..n** — intensity starts working.`);
w(`4. **Combat stacks** — the combat toggle starts working.`);
w(`5. **Second variants**, then the rest of the bed library.`);
w();
w(
  "Until a file exists, keep it out of the resolver so the console stays quiet about it: " +
    "`assetLayout({ base, ext, available: urlsYouHaveUploaded })` returns `null` for anything " +
    "not in the set, and `missingAssets(config, uploaded)` tells you what is still outstanding."
);
w();

writeFileSync(out, lines.join("\n"));

console.log(`${out}: ${summary.total} files (${summary.music} music, ${summary.beds} beds)`);
for (const t of summary.byTheme) {
  console.log(`  ${t.name.padEnd(18)} ${t.variants} variants × ${t.layers} layers = ${t.music} stems`);
}
